- src/book.json
ページの読み込みが重い直接の原因ではないかもしれないが、
いずれにせよファイルが大きい(9MB)ので、一旦無効化
ref https://github.com/dwango/scala_text/issues/8
> search_index.jsonの生成をしない

- src/implicit.md
トレイトやメソッドの定義で、実行はしていないので
REPLの形式になっていないほうが見やすいと思ったので
> いくつかのコード例をtut:slientに変更

- .travis.yml
fix #14
しばらくずっとインストール失敗はしていないし、もしなにかインストールでトラブった場合は再びdev/nullやめればいいので
> calibreインストール時のログが長くて邪魔なのでdev/nullへ

- .travis.yml
- project/Build.scala
- project/GitBook.scala
gitbook-cliにバージョン指定機能があることに気がついたので明示するようにしました。
指定しない場合は、  gitbook-cliで初めてビルドを行った時の最新バージョンが`~/.gitbook/versions` にインストールされ、そのバージョンでビルドが行われます。
いまどのバージョンでビルドしているのか良く分からなくなったり、手元だと古いバージョンのままビルドが行われるが、travisでは毎回新しいgitbookのバージョンでビルドされる？といった環境の差異の原因にもなるので明示したほうが良さそうです。
（指定したバージョンが無かったら自動でインストールしてくれるようなので、インストール処理などは追加しなくてよさそうです。）
> gitbookのバージョンを明示

- package.json
textlint側で早速対応していただけたので、バージョンを上げます！
https://github.com/textlint/textlint/releases/tag/5.4.1
ついでにリリースされていたbabel-preset-es2015もあげています。
> textlintのバージョンアップ

- package.json
- src/book.json
- src/collection.md
* [gitbook-plugin-regexplace](https://github.com/markomanninen/gitbook-plugin-regexplace) を使って実現
```
```
が現れたら、
```
<div id="$1" style="$2">
```
に置き換え
```
```
が現れたら、
```
</div>
```
に置き換え
* 綺麗ではないが、regexplaceを使えばmarkdownをHTMLのブロック要素で簡単に囲むことができる
> 解答例の折りたたみを実現

- src/error-handling.md
- src/future-and-promise.md
なぜConsole付きで呼び出していたのか？の意図は今となっては不明だが、
実際同じものだし
https://github.com/scala/scala/blob/v2.11.8/src/library/scala/Predef.scala#L315
特に大きな実害もないが、統一されてないのは気持ち悪いので
(printlnで呼び出してる箇所のほうが多く存在)
> Console.printlnをprintlnに置き換え

- project/NpmCliBase.scala
- project/TextLint.scala
example_projects以下のreadme.mdがtextlintに引っかかってしまう問題が発生したのでlint対象から除外します。
> example_projects以下ではtextlintを実行しない

- src/SUMMARY.md
`SUMMARY.md`では“java”となっていた表記を、記事のタイトルと同様に先頭が大文字の“Java”へ変更した。
> “java”を“Java”へ変更

- src/future-and-promise.md
たしかにjava.util.concurrent.Future自体には関数を引数に取るメソッドはないが、
そのサブクラスにそういったメソッドが存在する場合があるのは、
なんだか現状の説明では微妙に嘘ついてるというか説明不足な気がしたので、
脚注に一言くらいあってもいいかな、という気持ち
> CompletableFutureについて脚注を追加

- src/test.md
Scaladocの推奨スタイルは、いくつかJavaと違うので注意
http://docs.scala-lang.org/style/scaladoc.html
- `/**` の直後の1行目に書く(Javaでは書かない)
- 2行目以降の `*` の揃え方がJavadocと異なる(ただし、標準ライブラリでもこの形式になっていなかったりして、それほど守られてはいないが)
また、個人的にコメント書かないのにparamやreturnあるの無意味に感じるので削除
> Scalaコードのコメントの書き方微修正

- src/collection.md
fix #164 
ところで、毎回この`test`書いてるとミスりやすそうなので、まとめて定義したい感じがありますね…。
> reverseのテストを修正

- .bookignore
- .gitignore
- .travis.yml
- README.md
- book.json
- deploy.sh
- package.json
- project/GitBook.scala
- project/NpmCliBase.scala
#173 の出し直しです。
上げました。見た目に関する非互換な修正があるかもしれないのでビルド後のhtmlを一通り見る必要があります。 http://dwango.github.io/scala_text_previews/gitbook-v3
以下、あんまり読まなくても良いトラブルシュートです。
```
前提
- tut通す都合上、srcファイルをtutで変換してgitbookディレクトリにコピー => gitbook buildみたいな普通やらないプロセスになっていた
- 中間生成物が入るだけのgitbookディレクトリは当然 gitignoreに入れていた
v3に上げたときおこったこと
- gitbook build gitbook/のように実行すると、`gitbook/node_modules` を作らないとpluginが解決されないようになった。（バグ？）
- 上記の事柄自体はbook.jsonにrootプロパティを指定やれば解決する
- gitbookの仕様的にgitignoreに指定されているファイルはビルドに含まれないようになっている(v3よりも前からそういう仕様)
- v3に上げる前まではrootプロパティを指定していなかったため、gitignoreに指定されている `gitbook` ディレクトリの無視設定はgitbookプロセスからは効かない状態だった。
- rootディレクトリ変更機能を使うようにしたので、gitbookディレクトリが実際に無視されるようになりfile not foundが多発した
- `.bookignore`で強制的にビルドに加える設定を行って↑の問題を回避した
```
fix https://github.com/dwango/scala_text/issues/172
> Gitbookをv3にアップデート

- src/trait.md
Fix #184 
* トレイトの制限を回避するという方向の説明は、そもそも、トレイトがその制限を意図したものであるということを考えると妙な話なので、トレイトが通常どのように使われるか、という方向の説明に修正。
> traitの説明を改善

- src/error-handling.md
> 解答例に`map`が用いられているのに問題文になかったので追加

- src/function.md
ローンパターンという言葉自体があったほうがレビュー時などの意思疎通が図りやすそうでしたので追加してみました。
また実際のコードではaroundまで抽象化せず、`withFile`のようなリソース確保のロジックも担当するような関数での利用が多い（主観ですが・・）と思ったので抽象化のレベルを落とした例も併記しました。
議論
- 今までloan-patternという用語をあえていれていなかったので、それをいれたほうがよいか再び話したほうが良さそう
> ローンパターンの解説を追加

- deploy.sh
`deploy.sh`にある`mkdir`はブランチ名のフォルダを作るために呼び出されるが、たとえばブランチ名が`yyu/fix-something`のようにスラッシュを含むと失敗してしまう。
そこで`-p`オプションを追加し、スラッシュを含むブランチについても失敗しないようにした。
> mkdirのオプションを修正

- src/type-parameter.md
> 型変数の命名ルールを統一

- build.sbt
- project/plugins.sbt
- src/advanced-trait-di.md
- src/basic.md
- src/collection.md
- src/error-handling.md
- src/example_projects/trait-example/build.sbt
- src/example_projects/trait-refactored-example/build.sbt
- src/function.md
- src/future-and-promise.md
- src/implicit.md
- src/object.md
- src/sbt-compile-execute.md
- src/sbt-install.md
- src/test.md
依存ライブラリの修正などは含まずテキストの中身を変更しているため現段階ではテストが通りません。
本文のビルドは出来る状態。
#118 をリバートした関係でチェック出来なくなっているがscoverageが未対応。
sbt-scoverage 1.5.0-RC2が依存しているscoverage 1.3.0-RC1がscala 2.12.0-RC1をサポートしているらしいのでもう少し待つ。 https://github.com/scoverage/scalac-scoverage-plugin/releases
> Scala 2.12対応

- project/GitBook.scala
3.2.0 ~ 3.2.2 https://github.com/GitbookIO/gitbook/blob/3.2.2/CHANGES.md
markdown parserが変わりそうで変わってない（ロールバックした）ようなのであまり変更はなさそうです。
> gitbookバージョンを3.2.2へ更新

- README.md
- project/GitBook.scala
- project/plugins.sbt
二度目以降はキャッシュしたものを使うので爆速です
手元で計測
|コマンド|時間|
|:--|:--|
|`time sbt BuildHtmlQuick` 1回目|`289.58s user 10.16s system 200% cpu 2:29.36 total`|
|`time sbt BuildHtmlQuick` 2回目|`51.25s user 2.71s system 122% cpu 44.019 total`|
|`time sbt BuildHtmlQuick` 3回目|`50.46s user 2.75s system 119% cpu 44.394 total`|
|`time sbt BuildHtml`|`271.26s user 7.76s system 196% cpu 2:22.34 total`|
> tutをアップデート(tutQuickが追加されたのでコマンドも追加）

- src/test.md
もとからだったのか、最近のversionで変わっていたのかはわからないが、
coverageReportを最後に実行しないとhtmlが生成されなかったので追加した
> scoverageの記述修正。 fix #251

- src/type-parameter.md
後述で[A]を出してるのでここの定義は[A]とするのが良いと思いました。
> 後述の記載とつじつまが合うよう修正。

- book.json
- package.json
forkmeボタン https://github.com/mizunashi-mana/gitbook-plugin-forkmegithub を追加してみました。
また現状のscala_text( https://dwango.github.io/scala_text/ )はJSでエラーが出ているため正しくプラグインが機能しない状態だったようです。(そのため-searchがある状態だとボタンが表示されない）
久しぶりにsearchつけてみたところ、高速化されていたようでそこそこ使える雰囲気を感じたのでこの際ONにしてみました。
> 検索の復活 & Forkmeボタン追加

- src/future-and-promise.md
私の環境(Mac OS 10.10.5, Scala 2.12.1)では、PromiseSampleがprintlnを完了する前にプロセス終了することがあります。修正後のコードの方が、printlnが完了してからプロセスが終了する可能性が高いと思います。
> Promiseの例でprintlnが確実に実行されるよう修正

- src/future-and-promise.md
https://github.com/dwango/scala_text/pull/260#issuecomment-266973576 に相当するPRです。
#260 でonCompleteの処理終了を待てていなかったのがSleepの追加によって修正されました。
このPRではAwaitのほうが待ち時間が少なくなるため、Awaitを使いやすいようにコードを改変した上で待機をAwaitに変更します。
> futureの終了待機をSleepからAwaitへ

- src/error-handling.md
- test/mocha.opts
Eitherの説明部分は2.12を前提としている（map, flatMapの適用にRight, Leftの指定は不要）ようでしたので、Tryの説明に出るこの記述は2.11までのEitherの仕様であり、不要ではないかと考えました。
> 2.11までと思われるEither仕様の記述を削除しました。

- .travis.yml
現状特に困ってないが、なぜかtravisのデフォルトだと 1.8.0_31 という、
中途半端に古いversionのため
> travis-ci 上で最新のJava8を使う

- src/object.md
#205 において、[コンパニオンオブジェクトの説明](https://dwango.github.io/scala_text/object.html#コンパニオンオブジェクト) の object中の処理がメソッドに変更されましたが、その下にある `:paste` コマンドを使った例の方がそのままになっている気がします。
> コンパニオンオブジェクトの説明で :paste コマンドを使った場合の例もメソッドに変更

- src/test.md
サンプルのコードのままだと
```
[error]  value millis is not a member of Int
[error]     failAfter(1000 millis) {
```
といったエラーが出ます。
直前のサンプルから
`import org.scalatest.time.SpanSugar._`
が抜け落ちているせいだと思うので追記しました。
> テストのモックサンプルコードの修正

- src/future-and-promise.md
* `for`の`yield`で直接`print`するのではなく、`Await.result`で結果を取得して`println`するようにした。
> FutureとPromiseに関するサンプルコードのバグを修正

- deploy.sh
- fork先でtravis有効にしてもpushしないようにTRAVIS_REPO_SLUGもチェック(今までもどうせ失敗はするので害はなかったが)
- travisのcronのときにはpushしないように修正
https://docs.travis-ci.com/user/environment-variables/
> htmlやpdf生成してgit pushする際のチェックを追加

- src/example_projects/trait-example/project/build.properties
- src/example_projects/trait-refactored-example/project/build.properties
https://github.com/dwango/scala_text/pull/292 に書いたように、example_projectsのほうは、もうしばらく0.13にしておく？が、そうだとしても微妙にsbtのversion古いのに気がついたので、0.13系の最新の0.13.16にあげておく
> example_projectsのsbt versionを0.13.16に

- build.sbt
- src/sbt-compile-execute.md
- src/sbt-install.md
- src/test.md
つまり https://github.com/dwango/scala_text/commit/6067c05053612993558f7a6fdb543394fa6f1c21
を、さらにまたrevertし、revertによるコンフリクト解消
> Scala 2.12 に依存したsbt 1.0 が出たので、再びsbtのコードをtutでコンパイルする

- src/introduction-to-typeclass.md
https://github.com/dwango/scala_text/pull/286  との差について
- `Dividable` は不自然なので、 `Num` と `FromInt` 型クラスにした
- tutはREPL上で実行される都合上、コンパニオンオブジェクトにするために名前空間を追加
- `Nums`, `FromInts`
- この辺うまい解決策があったら教えてください
> 型クラスへの誘いの章を書き始め（途中なのでSUMMARYには入れてない）

- src/sbt-install.md
[simple build toolで検索](https://github.com/sbt/sbt/search?utf8=%E2%9C%93&q=simple+build+tool&type=)してヒットしなかったのですが、まだSimple Build Toolと言われているんでしょうか。
> Simple Build Toolという表現を削除

- README.md
<hr />
現状↑
何度か試したけれど、スペース空けていい感じに箇条書きをネスト(?)させるのがうまくいかないので、 `###` を使うように変更した
> READMEの"フィードバック"部分のレイアウトが崩れているので修正

- src/example_projects/trait-example/project/build.properties
- src/example_projects/trait-refactored-example/project/build.properties
- src/sbt-install.md
- src/test.md
fix https://github.com/dwango/scala_text/issues/293
上記issueでの議論にもあるように、もうplayframework含め、大半のsbt pluginは1.0対応したので、このテキストでも1.0推奨にする。
本文中で言及しているscoverageとscalastyleのpluginに関しては、最新にversionをあげればsbt 1.0対応済だったので、最新にあげた
> sbt 1.0を使う

- .travis.yml
プレビュー表示されるはずのURL
http://dwango.github.io/scala_text_previews/nodejs-latest/
> nodejsを最新安定版にする

- deploy.sh
https://github.com/dwango/scala_text/commits/gh-pages
2017-11-29を最後にpushに失敗している。
なんで失敗してるのか、多少原因の検討はついているが、より正確に原因をわかりやすくするために、まずコマンドがどこまで実行されたか？を、全部わかるようにする
```
error: Your local changes to the following files would be overwritten by checkout:
package.json
Please commit your changes or stash them before you switch branches.
Aborting
```
> デプロイ(gh-pagesへのpushなど)が失敗した場合にエラー箇所をわかりやすくする

- deploy.sh
https://github.com/dwango/scala_text/issues/396 に現象(package-lock.jsonが変更されてる？)を書いたが、これがベストな解決方法なのか？は、議論の余地あるかもしれないが、travis-ciのログ見て、直りそうなら一旦これをmerge？
> gh-pagesへのpushに失敗する問題を解決

- .travis.yml
- package-lock.json
JavaScript詳しくないので package-lock.json がどうなっているべきか、完全にはよくわかってないが、おそらくgitbook生成のコマンド実行後に  package-lock.json が書き換わってしまうらしい？
- https://github.com/dwango/scala_text/issues/396
- https://github.com/dwango/scala_text/issues/377
gitbookのコマンド実行しても書き換わらない状態のものを登録しておく(それをチェックする)なら、こういうコマンドを実行してチェックしておくべき？
(ちなみにgitbookのコマンドはsbt経由で実行してる)
> gitに登録されているファイルに差分があったらビルドを失敗にする

- src/control-syntax.md
> `do while`文もありますが、ほぼJavaと同じなので説明は省略します。
上記の表現では、「**Scalaには** `do while`文もあります」と解釈できます。
`do while`はUnit型の値を返す以上、 `do while`**式**という書き方が適していると思います。
> Fix: do while文 -> do while式

- src/test.md
Fix https://github.com/dwango/scala_text/issues/416
> 非推奨のorg.scalatest.concurrent.Timeoutsをorg.scalatest.concurrent.TimeLimitsに修正

- src/collection.md
- src/future-and-promise.md
- src/implicit.md
- src/java-interop.md
以前とURLの形式が変わったため、rootパッケージに飛ばされてしまっていた
Fix #422
> Scala APIへのリンクを修正

- src/sbt-install.md
「最新のScalaは、Java 9 や 10 でもだいたい動くけどまだちょっとだけ問題ある場合あるので、まだやめておいたほうがいい。あとJava 11が出るまでは、Java 9や10は〜」
みたいなことを書こうか迷ったが、数ヶ月〜1年くらいでその記述も古くなりそうなので、Scala公式サイトのリンクを貼るだけにした
> Javaのインストールについて追記

- src/control-syntax.md
Fix #425
別途、高階関数の説明の部分で、 `break` や `continue` を代替できるという説明があった方が良い
かとは思います。
> breakやcontinueがないことに関する補足

- src/basic.md
直前に、 `dbl.asInstanceOf[Int]` が使えるということを説明しているため。
> asInstanceOfの入力例を追加

- src/trait.md
一時的なものなのか、恒久的なものなのか？はわからないがエラーになるので。
dottyのトップページから
https://dotty.epfl.ch/
このSIPのページにリンクされていたので、これに差し替え
> http status 404になるurlを差し替え

- deploy.sh
dwango退職するので。
https://xuwei-k.hatenablog.com/entry/2019/01/17/232917
別にここを変えないままでも自動でgithub pagesにpushする動作に特に支障はないが、一応変えておく。
pdfのほう
https://github.com/dwango/scala_text_pdf/pull/9
と同様に、ひとまずkmizuさんにしておく。
ここで実在のアカウントに紐付いたemailにすると、良くも悪くもcontributionにカウントされる(草生える)気がするので、本来botアカウント的なものにしたほうがいいかもしれないが、規約上githubは無料枠で勝手にbot作るとbanされたりするので(されたことがある)。
もしくは、存在しなそうな適当なemailにする、gmailのalias使う、などの手はある？がどうするか 🤔
> gitのcommitに使うuser.email, user.nameを変更

- src/collection.md
`Nil`周りで型注釈を付ける必要がある場合があるが、その解説がない件（ #493  ）への対応。
Scalaの型理論・型推論よくわかってないので、とりあえずふわっと書いてみましたが、妥当がどうかは意見いただきたいです。
> 型注釈について追記。 close #493

- README.md
- book.json
- deploy.sh
- src/INTRODUCTION.md
- src/advanced-trait-di.md
- src/exercises.md
- src/sbt-install.md
https://github.com/scalajp/scala_text/issues/505
とりあえず  https://dwango.github.io/scala_text/ などが404でエラーでCI通らない状態なので、簡単に書き換え可能な部分だけ書き換え。移行作業はこれで全てではないが、ひとまず
https://travis-ci.org/scalajp/scala_text/builds/589803097
> dwangoをscalajpに書き換え

- README.md
リポジトリ作ったので、今度はエラーにならないはず
(pdf自体の自動更新の仕組みはおそらく動いてないが、それは別問題なので後で)
> PDFのURLもdwangoからscalajpに変更

- README.md
- book.json
- deploy.sh
- src/IDE.md
- src/INTRODUCTION.md
- src/advanced-trait-di.md
- src/exercises.md
- src/sbt-install.md
> scala-text orgへの移管に伴ってURL書きかえ

- src/control-syntax.md
初めてのOSSへのCommitなので不手際ございましたらご了承ください。
https://scala-text.github.io/scala_text/control-syntax.html#%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E3%83%9E%E3%83%83%E3%83%81%E3%81%AB%E3%82%88%E3%82%8B%E5%80%A4%E3%81%AE%E5%8F%96%E3%82%8A%E5%87%BA%E3%81%97
こちら部分のインデントがズレていたので修正です。
> インデントずれの解消

- src/trait.md
[菱形継承問題](https://scala-text.github.io/scala_text/trait.html#%E8%8F%B1%E5%BD%A2%E7%B6%99%E6%89%BF%E5%95%8F%E9%A1%8C)でエラーの文面が掲載されていなかったので追記しました。
> トレイトのエラーの例(競合するメンバーの継承)を追加

- .travis.yml
- package-lock.json
- package.json
- src/implicit.md
- `npm install svgexport -g` の際にoptional catch bindingを使ったファイルの処理に失敗していた
- https://github.com/tc39/proposal-optional-catch-binding
- Nodeのバージョンを上げたところ一部node-gypの関係で動かないパッケージがあったのでそれは一緒に更新
- `sleep`
- `package-lock.json` があるので `npm ci` の方を使用するようにした
- package.jsonの中がだいぶ古くなっているので更新した方が良さそう
- gitbookはメンテされてないので [honkit](https://github.com/honkit/honkit) に移行する？
- `npm install svgexport -g` はバージョンが固定されないので今回のような問題を起こしがちなのでなんとかした方が良さそう
fixes #563
> CIで使用するNodeのバージョンが古く、動かなくなっているのを修正

- src/java-interop.md
下記でレイアウト崩れが確認できました。
https://scala-text.github.io/scala_text/java-interop.html#%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%AE%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%97
見てみたところ、mdocが `System.out.println` に反応していないので一旦mdocを使わないようにしてレイアウト崩れを回避しています。
|Before|After|
|---|---|
|<img width="1438" alt="Screen Shot 2021-01-24 at 18 44 03" src="https://user-images.githubusercontent.com/24843808/105626742-1ca9b280-5e75-11eb-8311-e7e426ce61b9.png">|<img width="1439" alt="Screen Shot 2021-01-24 at 18 46 31" src="https://user-images.githubusercontent.com/24843808/105626736-19162b80-5e75-11eb-8846-b3aac883430b.png">|
---
ps: このプロジェクトは初めてでもわかりやすくて助かります...! ありがとうございました。
> Javaとの相互運用>インスタンスメソッドの呼び出し>練習問題のレイアウト修正

- src/sbt-install.md
#555  の対応。
簡単ですが、書いてみました。ご確認くださいm(_ _)m
Macとjavaのインストールもsdkman!にした方がいいんじゃないかなって気もしますが、別スコープということで。
> sbt installのLinux環境の記述追加 #555

- src/sbt-install.md
JDK8で `java -version`をすると
```
$ java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)
$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
のようになってしまうようなので、fix.
- https://www.ne.jp/asahi/hishidama/home/tech/java/version.html
> `java --version` はJDK８以下では動作しない

- src/sbt-install.md
> M1かつJava 11以前を利用している場合、M1対応のZuluを利用する方が多少速いことを注釈に入れる。

- src/test.md
- 動くようになってるはずなので`動かない`という記述削除
- SCCTの歴史的経緯はかなり昔でもう必要ない気がするので削除
- versionを最新に更新
> scoverageに関する記述更新

- README.md
- 解釈が難しい文言であるため
- 厳密に言えば参考にした文言は4.0ベースのものであるが、 3.0->4.0でこの部分が変わったと思われないので良さそう
> CC-BY-NC-SA 3.0の「非営利」「ライセンスの継承」について追記

- src/function.md
```
warning: function.md:226:5: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method getLines,
or remove the empty argument list from its definition (Java-defined methods are exempt).
In Scala 3, an unapplied method like this will be eta-expanded into a function. [quickfixable]
file.getLines.foreach(println)
^^^^^^^^^^^^^
```
> 警告修正。getLinesに括弧付与
