scala-text/scala_text

README.md
test/link.js

なぜかこのコミットをfork先にpushすると失敗するけど、こっちだと成功する、みたいな謎が残っているが

privateだったときの記述の残骸(必要なくなっている)を削除

---

.travis.yml

以下のあたりにテストがあるが、おそらく実施されていなかった
https://github.com/dwango/scala_text/blob/99dbd63da/src/example_projects/trait-refactored-example/src/test/scala/domain/UserServiceSpec.scala

travis上で "sbt test" も実行するように修正

---

src/future-and-promise.md

https://github.com/dwango/scala_text/pull/6 で頂いた意見を元に、
- 並行処理について色々解説が必要そうなところはありそう
- Scalaの教科書でどこまで書くか・書くとしてもすぐには出来上がらなさそう
という話を踏まえて、勉強したい人はこれを見るといいですよという案内を一旦つけてみました。
(Effective Javaも10章で並行処理について扱っているので入門には良さそうだと思います。)

参考文献リンクを追加

---

package.json
src/book.json

* https://github.com/rlmv/gitbook-plugin-anchors
* See also: #26 
* 特定のセクションにリンクを貼れるようになる…ので便利になるはず

gitbook anchors pluginを導入

---

project/plugins.sbt

ほぼ影響ある変更ないけど、一応上げておく
https://github.com/tpolecat/tut/compare/v0.4.1...v0.4.2

tutを0.4.1から0.4.2へ

---

project/Build.scala
src/advanced-trait-di.md
src/basic.md
src/collection.md
src/error-handling.md
src/example_projects/trait-example/build.sbt
src/example_projects/trait-refactored-example/build.sbt
src/function.md
src/object.md
src/sbt-compile-execute.md
src/sbt-install.md
src/test.md

Update to Scala 2.11.8

---

src/trait.md

微妙に不正確な説明を削除

---

src/control-syntax.md

制御構文の練習問題に一意のIDを振った

---

src/control-syntax.md

制御構文の練習問題、解答例が足りないので、あとで追加しよう…

制御構文の練習問題の解答を折りたたみ形式に変更

---

src/implicit.md

「implicitの値が解決される探索される範囲」という変な日本語を修正

---

src/control-syntax.md

入れ忘れたことにより、解答が隠れてない
http://dwango.github.io/scala_text/control-syntax.html#control_syntax_ex3

style="display:none" の入れ忘れ修正

---

src/collection.md

foldLeftを利用した解答に修正

---

src/control-syntax.md

* これ、実は設問がよくないという気はする。素直に読むと、最初と最後の文字が一致するケースがでるまで延々とループして、というのを1000回繰り返さなければいけないように読める。
* 設問にも修正を入れる

制御構文の練習問題の解答例を追加

---

src/future-and-promise.md

Semaphoreの実装例に関する問題を削除

---

project/Build.scala
src/test.md

typoも修正( s/asserr/assert )
https://github.com/dwango/scala_text/issues/90 というissueあるので、それが完了したらあまりこの変更意味なくなる可能性あるが、ひとまず

test.mdでtut使用

---

project/Build.scala
src/test.md

ScalaMockからMockitoへ置き換え

---

project/Build.scala
src/sbt-compile-execute.md
src/sbt-install.md
src/test.md

sbt0.13はScala2.10で使えないので、sbt 1.0のマイルストーン使った

sbtのビルドファイル関連でtut使用

---

src/control-syntax.md

練習問題の問題のコードがよくないのを直した

---

src/control-syntax.md

問題文では「アルファベット」とあるのですが、解答例のコードでは数字も出力され得ます。
学習順序も考慮し、問題文を修正するほうが本来の意図通りかと思いそのようにしました。

制御構文最後の練習問題で、問題文と解答例が合致していなかったので修正

---

README.md

- 成果物（HTML, EPUB, PDF）へのリンクを追加
- PDFの生成方法はサポートされていないので削除

成果物へのリンクをREADMEへ追加

---

test/link.js

src/example_projects内の`index.scala.html`などへのリンクがあると
`index.scala.md` を探しに行こうとしてテスト失敗するケースがあったため対応

link.jsの修正

---

src/example_projects/trait-example/build.sbt
src/example_projects/trait-refactored-example/build.sbt

https://github.com/scalikejdbc/scalikejdbc/blob/2.4.1/notes/2.4.1.markdown

scalikejdbcを2.4.1にアップデート

---

src/trait.md

fix #170
http://dwango.github.io/scala_text_previews/trait-tut/trait

trait.mdでtut使用

---

src/collection.md

回答となるメソッドのシグニチャを追加

---

project/plugins.sbt

https://github.com/tpolecat/tut/compare/v0.4.2...v0.4.3

tutを0.4.2から0.4.3にアップデート

---

project/build.properties
src/example_projects/trait-example/project/build.properties
src/example_projects/trait-refactored-example/project/build.properties
src/sbt-install.md

https://github.com/sbt/sbt/blob/v0.13.12/notes/0.13.12.markdown

sbt 0.13.12

---

src/type-parameter.md

EmptyStackの使用例を追加

---

src/control-syntax.md

テキストでforの中のifについて説明しているので、練習問題ではそちらを使った回答を求められてると解釈される
受講者の指摘

for式の演習問題のifをforの中のものにした

---

src/object.md

object中のコンストラクタの処理をメソッドに変更

---

src/future-and-promise.md

fix #213 
文章を治すついでに例を変えてみたのですがいかがでしょうか・・？

Promiseの例をtrySuccessからコールバックのラップに変更　fix #213

---

src/IDE.md
src/case-class-and-pattern-matching.md
src/collection.md

私がscala_textを用いて勉強した際に、ちょっとわかりにくかった点、こうすればわかりやすいと思った点をまとめました。  
ご検討ください :D

各所の微細なテキストを修正

---

src/error-handling.md

いずれ変わる可能性がありますが、現段階でつけるのは無駄ではなさそうなので
https://github.com/dwango/scala_text/issues/224#issuecomment-250568089

sealedが付けられそうなところにsealedを付与

---

src/java-interop.md

存在型の説明をワイルドカードと関連した話として追加した

---

src/typeclass.md

identityの定義を追加

---

README.md
src/INTRODUCTION.md

フィードバックの項目を追加

---

build.sbt
project/plugins.sbt

tutとscalacheckを最新にアップデート

---

build.sbt

https://github.com/rickynils/scalacheck/compare/1.13.3...1.13.4

scalacheck 1.13.4

---

project/GitBook.scala
src/styles/website.css

アドホックな解決をしたままだったので正式な対応を取ります。
ref: http://qiita.com/nacika_ins/items/24b91f654cf2dc59dd81

css replaceを削除

---

src/future-and-promise.md

promiseの例を別スレッドから値を設定するように変更 fix #217	

---

build.sbt
src/advanced-trait-di.md
src/basic.md
src/collection.md
src/error-handling.md
src/example_projects/trait-example/build.sbt
src/example_projects/trait-refactored-example/build.sbt
src/function.md
src/implicit.md
src/object.md
src/sbt-compile-execute.md
src/sbt-install.md
src/test.md

update scala 2.12.1

---

build.sbt
src/advanced-trait-di.md
src/basic.md
src/collection.md
src/error-handling.md
src/example_projects/trait-example/build.sbt
src/example_projects/trait-refactored-example/build.sbt
src/function.md
src/implicit.md
src/object.md
src/sbt-compile-execute.md
src/sbt-install.md
src/test.md

fix https://github.com/dwango/scala_text/issues/267

Scala 2.12.2

---

project/build.properties

- http://eed3si9n.com/ja/sbt-01315
- https://github.com/sbt/sbt/blob/v0.13.16-M1/notes/0.13.15.markdown

sbt 0.13.15

---

project/plugins.sbt

0.5.1バグってたらしい？
- https://github.com/tpolecat/tut/blob/v0.5.2/CHANGELOG.md#new-and-noteworthy-for-version-052
- https://github.com/tpolecat/tut/compare/v0.5.1...v0.5.2

tutを0.5.2にアップデート

---

src/case-class-and-pattern-matching.md

findとfindBinaryTreeをいったん回答例から退避

---

.travis.yml

fix https://github.com/dwango/scala_text/issues/301

npm install svgexport -g を実行する

---

src/class.md

メソッド定義に関して説明を改善

---

src/case-class-and-pattern-matching.md

`find`と`findBinaryTree`を削除

---

src/IDE.md

IDEの章の說明で誤っていた部分を修正

---

src/class.md

複数の引数リストについて補足

---

src/sbt-install.md

この前 https 対応していたので、ついでに https にした

sbtのURLが404になるため更新

---

src/introduction-to-typeclass.md

context boundsを使ったコードを追加

---

package-lock.json
package.json

* 最近のnpm ではこれを使ってバージョンを固定するのが普通っぽい（？）
* Gemfile.lock みたいなもんだと理解

package-lock.json を追加

---

src/introduction-to-typeclass.md

型クラスの章を一通り書いた

---

src/SUMMARY.md

* 章全体のレビューはしてもらってないので、とりあえずβ版とつけといた

型クラスの章をトップページからたどれるようにしてみた

---

src/introduction-to-typeclass.md

- See https://github.com/dwango/scala_text/issues/400#issuecomment-366734295

コードをより説明的にしてみた

---

src/example_projects/trait-example/build.sbt
src/example_projects/trait-refactored-example/build.sbt

- https://github.com/scalikejdbc/scalikejdbc/compare/3.2.1...3.2.3
- https://github.com/scalikejdbc/scalikejdbc/blob/64103b5182634e79251235033a15d4cc071b421e/notes/3.2.2.markdown

scalikejdbc 3.2.2

---

src/error-handling.md

エラー処理の章のAPIドキュメントへのリンクを修正

---

src/future-and-promise.md

カウントダウンラッチの問題の回答例を修正

---

build.sbt

以下のコミットでの上げ忘れ
https://github.com/dwango/scala_text/commit/f6151ba1bb62840ae97c0a2e736bfafe8004c3d7

update Scala 2.12.6

---

package-lock.json
package.json

よくわかってないけど `npm audit fix --force` をしたらこうなった。
(たぶん) fix https://github.com/dwango/scala_text/issues/411

jsの依存をアップデート

---

src/class.md

クラス定義の練習問題と模範解答・解説を追加

---

src/introduction-to-typeclass.md

型パラメータ名の誤字を修正

---

src/introduction-to-typeclass.md

サンプルコードのバグを修正

---

src/test.md

100万のところは1000万であるべき

---

.travis.yml
package-lock.json
package.json

package-lock.json の不整合を解消

---

src/case-class-and-pattern-matching.md

ケースクラスに追加される性質についての節を追加。 close #494

---

build.sbt
src/advanced-trait-di.md
src/basic.md
src/collection.md
src/error-handling.md
src/example_projects/trait-example/build.sbt
src/example_projects/trait-refactored-example/build.sbt
src/function.md
src/implicit.md
src/java-interop.md
src/object.md
src/sbt-compile-execute.md
src/sbt-install.md
src/test.md

fix https://github.com/scala-text/scala_text/issues/504

Scala 2.13.1

---

.bookignore
.github/workflows/ci.yml
.gitignore
README.md
book.json
build.sbt
package-lock.json
package.json
project/Honkit.scala
project/NpmCliBase.scala
test/link.js

fix https://github.com/scala-text/scala_text/issues/518
公式の手順通りにやったらそのまま動いた、最高便利
- https://efcl.info/2020/06/19/githon/
- https://github.com/honkit/honkit
package-lock.jsonの更新方法が合っているのか謎だけど(ローカルでちゃんとnodeなどのversion合わせられてなかった疑惑)、まぁエラー出てないし、botが更新する仕組み入れてあるから、後でbotがいい感じにしてくれるはず(?)
https://github.com/scala-text/scala_text/pulls?q=is%3Apr+author%3Aapp%2Fdependabot

開発が止まっているgitbookからhonkitへ移行

---

src/future-and-promise.md

https://docs.scala-lang.org/scala3/book/methods-main-methods.html

Scala 3以降でうまく動かなくて実質非推奨なので `scala.App` の使用やめる

---

src/IDE.md

- https://github.com/scala-text/scala_text/issues/862
他の追加どうするか？は別pull reqで

`Scala IDE for Eclipse` の記述削除

---

src/control-syntax.md

replace do while with while

---

src/java-interop.md

チェックするプログラム入ってるはずだけど検知されていないのは、Scala公式が4xx以外を返してるのか、あるいは…？？？

CollectionConvertersのlink修正

---

src/trait.md

issueで下記の記載があったのでPRを作成しました。
> 2022/07/04（月）のもくもく会で決まったこと
>単純に消す（現状のScalaでもほぼ使わないので）

#552 Early Definitionsの記述を削除

---

.github/workflows/ci.yml

- これの暫定対策 https://github.com/scala-text/scala_text/issues/1018

epub生成を一旦無効化

---

README.md
src/INTRODUCTION.md

- https://github.com/scala-text/scala_text/issues/1018

epub無効化したのでリンク切れなので一時的に削除

---

.github/workflows/ci.yml

- fix https://github.com/scala-text/scala_text/issues/1018

epubを再度有効化

---

.github/workflows/ci.yml

本来もっと上げたいが、動くかどうか謎なので、とりあえず14.xの最新にした

update node version

---

README.md
src/INTRODUCTION.md

- Reverts scala-text/scala_text#1021
- 直ったので https://github.com/scala-text/scala_text/pull/1023

Revert "epub無効化したのでリンク切れなので一時的に削除"

---

src/java-interop.md

- https://github.com/lampepfl/dotty/commit/e3af2de36566f7f8ca382cc1fdf33e386f15fa03
- https://github.com/scala/scala/commit/41989699a9f64711e60ffafe8e27010748f2068a
- https://github.com/scala-text/scala_text/commit/47cb87b6da5c2a6a4859750fa7aa197e2dc59351

ワイルドカードを`_`から`?`に修正

---

README.md
src/INTRODUCTION.md

- https://github.com/scala-text/scala_text_pdf/pull/77

本文のCCライセンスとREADMEのリンクを修正

---

src/INTRODUCTION.md

`INTRODUCTION.md`のライセンス文言をREADMEとあわせた

---

.github/workflows/ci.yml
build.sbt
src/basic.md
src/example_projects/trait-example/build.sbt
src/example_projects/trait-refactored-example/build.sbt
src/sbt-compile-execute.md
src/sbt-install.md
src/test.md

数年前に色々話をしたが、結局中途半端なままずっとScala 2になっており、細かくScala 2と3の両方を綺麗に書いていくリソースというか、やる気がある人もいないし、流石にそろそろもう雑にScala 3をデフォルトにしてしまって、今後のことは随時考えるというか、出来る範囲で最低限やっていくことにする

Scala 3に変更
